### ISSUE TITLE
What IRC channels are you in?

### ISSUE THREAD

**Issue by sindresorhus** [bwinton/ama#14]

**Comment by bwinton** [comment]
On Freenode I’m on:
* #nikola (my current blogging software) and
* #pyblosxom (my previous blogging software).

On MozillaIRC I’m on:
* #maildev - because I'm still the UX Lead for Thunderbird.
* #toronto - to keep up with lunch plans and office chatter.
* #vancouver - because I used to work with a lot of Vancouverians.
* #airmozilla - for back-chat during the Monday Meetings.
* #fx-team - to see what the Firefox engineers are working on.
* #ux - for hopefully obvious reasons.  :smile:
* #mofodesign - because the Mozilla Foundation designers are both really nice and have interestesting things to say.
* #mobile - to see what’s coming in Android and iOS Firefox development.
* #animatedgifs - to get new submissions for [Whimsy](https://github.com/bwinton/whimsy/blob/gh-pages/thumbnail-gifs.txt).
* #whimsy - for the same reason.
* #jetpack - to ask and answer Firefox [Add-on SDK](https://addons.mozilla.org/en-US/developers/docs/sdk/latest/dev-guide/) questions, and…
* #metrics - to find out what’s happening in our data-collection-and-reporting pipeline.

That seems like a lot, but most of them are pretty quiet.
