### ISSUE TITLE
Why people stress to use Immutable structures in javascript ?

### ISSUE THREAD

**Issue by annamalai-saro** [bwinton/ama#16]

**Comment by bwinton** [comment]
I think the biggest reason is that immutable data structures make it much easier to figure out what’s going on when you share data between functions.  (Like, imagine you had a function like
``` javascript
function print(x) {
  if (x.value === 3) {
    console.log('fizz');
  }
  y();
  if (x.value === 5) {
    console.log('buzz');
  }
}
var z = {'value': 3};
print(z);
```
What do you think it would print?  It turns out that it depends on what `y` does, since y could change `z.value`, so to understand `print`, you need to understand everything `print` calls.  (It also depends on what `console.log` does, which a lot of people forget!  ;)

For similar reasons, it also makes it easier to diff objects, because you know that they won’t change out from underneath you.  And if you ever want to move some of your code to run in a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) as an optimization, starting with immutable data structures will ensure you aren’t accidentally modifying the data in a way that would be impossible in a Worker.

Finally, @raganwald (whose [blog/site](http://raganwald.com/) you should definitely read, because it’s mind-expanding!) has a good blog post about them [over here](http://raganwald.com/2014/06/15/immutable-structs.html).

Thanks for the question!

**Comment by annamalai-saro** [comment]
Thanks !
