### ISSUE TITLE
what program do you prefer to use to compress your scss files into css? 

### ISSUE THREAD

**Issue by alohavolha** [bwinton/ama#18]
I am currently using prepros but it is very buggy. It is only a temporary fix as I am just learning sass but once I get better and could actually think in sass I would like to use a more efficient tool. What is your go-thank you

**Comment by bwinton** [comment]
Honestly, I just write plain CSS.  Most of the stuff I do isn't really complicated enough to bother with running a pre-processor of any sort.  Heck, I only started using [Babel](https://babeljs.io/) a couple of weeks ago, and then later found out I didn't need it after all, because the latest version of Chrome supports [fat-arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions).  :wink:
