### ISSUE TITLE
what are your thoughts on rems, ems, % and px?

### ISSUE THREAD

**Issue by alohavolha** [bwinton/ama#19]
what do you normally prefer to use px/%/em/rem? and why?
I was recently introduced to rem and looks like from now on I will only be using %, rem and occasionally px in my code.

oh, and what do you think about these guys ( i just came across it the other day and though it was interesting, especially the http://txti.es/about )
www.motherfuckingwebsite.com

Thank you!

**Comment by bwinton** [comment]
So, I like rem, but had to [remove them](https://bugzilla.mozilla.org/attachment.cgi?id=8589207&action=diff) from the reading mode in Firefox, because changing the font-size on the root element caused _everything_ to repaint, even things that weren’t changing size, which was slower than we were hoping.  For the prototypes I write, I mostly deal in px, because I don’t need to worry about what size people set their fonts to, and I want things to line up, but for production code, I recommend you don’t do that.  :wink:

As for those guys, I’m a little conflicted.  I mean, having a simple page that renders quickly and is responsive and accessible is really nice, but wow is that page ever ugly!  :smile: I think that there’s probably a happy medium somewhere in there with some CSS and images and JavaScript to make things more readable and easier on the eyes, but still keep the size down below [12 Mb](blog.lmorchard.com/2015/07/22/the-verge-web-sucks/)…  It’ll be interesting to see how Safari’s Content Blocking impacts the web.  Will it push publishers and advertisers towards making less heavyweight ads?  I don’t know…

Thanks for the questions!
