### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by wesbos** [bwinton/ama#2]
a la https://github.com/wesbos/ama/issues/2

**Comment by bwinton** [comment]
(I haven't had time to take a screenshot, but I swear I'll get to this soon!)

**Comment by bwinton** [comment]
Wow, did I ever lie about getting to this soon…

So, here’s the image:
![iPod Touch homescreen](https://cloud.githubusercontent.com/assets/159571/9013706/9bb5553c-378b-11e5-8339-6343e523e152.png)

There isn’t a lot of organization there, but the most-used things (or, more accurately, the things I wish I used most) are on the bottom.  I tend to switch between screens a lot, and use stuff on the bottom row or two of each screen, instead of staying on one screen and using it.  I’m also allergic to folders.  I have a "Social" folder on the next screen with Twitter/Instagram/Facebook/etc on it, but it takes a real effort to open it.  I also kind of cheated, by showing the device I use the most, which isn’t my Android phone.  :wink:
