### ISSUE TITLE
How did you and how do you get a job at Mozilla?

### ISSUE THREAD

**Issue by wesbos** [bwinton/ama#3]
What did you do to make yourself stand out? What did you do before Mozilla?

**Comment by bwinton** [comment]
Nepotism, mostly.  :smile:

No, not really.  I've posted [most of the story](https://weblog.latte.ca/blake/employment/mozilla/sixyears.html) on my blog, but the tl;dr was that I contributed a little to Thunderbird, who was looking for someone with my skills.  I also got a recommendation from a mutual friend, which I believe helped, but the contributions were both proof that I could work with the team, and a way to show that I could take long-standing, controversial bugs and drive them through to completion.

Would I recommend this for other people?  No, probably not.  Contributing to Firefox (or any of Mozilla’s other projects) should be done because you want to, not in the hopes of getting a job.  If you want a job, you should definitely [apply for it](https://careers.mozilla.org/en-US/), even if you think you're not qualified!  (There's no penalty for applying to more than one job, if there are a couple you're interested in.  And if you know someone who works here, send them your resume, both so that they can get the referral bonus and to get your resume past the initial screening.)

Before Mozilla, I worked writing mobile gambling games for Palm, PocketPC, and Blackberry (C++ on the client, Java on the server, and Python for some internal tools), writing financial webapps (in Java) and a Visual Basic to Java translator, working on an ASP-based document management system (think Subversion for lawyers), an HTML editor and website creator, and various other things in the early '90s.
